### ISSUE TITLE
spring boot 集成shiro-redis遇到问题

### ISSUE THREAD

**Issue by cjcj125125** [alexxiyang/shiro-redis-tutorial#1]
你好，看着你的示例写，我是在springboot中集成shiro-redis，但是提示错误： No SecurityManager accessible to the calling code..........好像是没有扫描到shiro.ini中的配置，请问是不是必须和你示例项目一样添加那些依赖？？谢谢

**Comment by CodePlato3721** [comment]
是的，目前还不支持spring boot 请手动添加依赖

**Comment by cjcj125125** [comment]
添加哪些依赖？？谢谢你的回复

**Comment by CodePlato3721** [comment]
只需要添加一条maven依赖，即shiro-redis的依赖。

报错的详细信息是什么？

**Comment by CodePlato3721** [comment]
你试试先配置好shiro但是不用redis，只用默认的内存缓存，再过度到shiroredis

**Comment by cjcj125125** [comment]
好的，我先试试

**Comment by cjcj125125** [comment]
我和你这个一样写的，但是一直提示  java.lang.ClassNotFoundException: com.xx.conf.ShiroRealm（com.xx.conf是路径名）
![qq 20180730163846](https://user-images.githubusercontent.com/20206579/43391775-2eca0a3c-9424-11e8-9817-402762a35e12.png)

**Comment by cjcj125125** [comment]
我和你这个一样写的，但是一直提示  java.lang.ClassNotFoundException: com.xx.conf.ShiroRealm（com.xx.conf是路径名）
![20180730180630](https://user-images.githubusercontent.com/20206579/43391849-5e17004c-9424-11e8-8a96-e16a4af07bec.png)

**Comment by cjcj125125** [comment]
我这边一直这个错误，麻烦指点下，谢谢




![qq 20180730182010](https://user-images.githubusercontent.com/20206579/43399050-62f7a856-943c-11e8-940b-aa90bb9518fa.png)
